Repository googleapis/nodejs-grafeas, pull requests merged in 2019-06, with the labels that each got.

#9 feat: support apiEndpoint override in client constructor
  protos/grafeas/v1/grafeas.proto
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#10 fix: get tests passing so that we can land and release module
  .gitignore
  package.json
  samples/test/.eslintrc.yml
  samples/test/quickstart.js
  synth.metadata
  synth.py
  system-test/test.js
  test/gapic-v1.js
Labels: cla: yes

#3 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: :rotating_light:, autorelease: pending, cla: yes, type: process

#11 docs: update return type in jsdoc for Buffers
  src/v1/doc/google/protobuf/doc_any.js
  src/v1/doc/grafeas/v1/doc_attestation.js
  src/v1/doc/grafeas/v1/doc_build.js
  src/v1/doc/grafeas/v1/doc_common.js
  src/v1/doc/grafeas/v1/doc_provenance.js
  synth.metadata
Labels: cla: yes

#12 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
  README.md
Labels: cla: yes

#14 refactor!: remove build signature support
  protos/grafeas/v1/build.proto
  protos/grafeas/v1/deployment.proto
  protos/grafeas/v1/provenance.proto
  src/v1/doc/grafeas/v1/doc_build.js
  src/v1/doc/grafeas/v1/doc_provenance.js
  synth.metadata
Labels: cla: yes

#16 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#15 chore: release 2.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#17 feat: add NoteKind enum
  src/index.js
  synth.metadata
  synth.py
Labels: cla: yes

#18 chore: release 2.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#19 fix(revert): revert exposing NoteKind enum; automate jsdoc fix
  src/index.js
  synth.metadata
  synth.py
Labels: cla: yes

#20 chore: release 2.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#21 fix: changes to default values in vulnerability.proto
  protos/grafeas/v1/vulnerability.proto
  src/v1/doc/grafeas/v1/doc_vulnerability.js
  synth.metadata
Labels: cla: yes

#23 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#22 chore: release 2.1.2
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#24 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes
