Repository googleapis/nodejs-grafeas, pull requests merged in 2020-08, with the labels that each got.

#186 test: limit results returned to speed up test
  package.json
  system-test/test.ts
Labels: cla: yes

#176 build: typo in gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#183 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: cla: yes

#187 fix: use gax protobuf reference
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#188 fix: update descriptor logic
  src/v1/grafeas_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#189 build: update docs and publish scripts
  .gitattributes
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  README.md
  api-extractor.json
  synth.metadata
Labels: cla: yes, context: partial

#191 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#194 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes, context: full
