Repository googleapis/nodejs-grafeas, pull requests merged in 2020-07, with the labels that each got.

#173 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#174 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#179 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#178 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes
