Repository googleapis/nodejs-grafeas, pull requests merged in 2020-11, with the labels that each got.

#211 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#212 build: add v1.GrafeasClient type
  src/index.ts
  synth.metadata
Labels: cla: yes, context: none

#213 fix: do not modify options object, use defaultScopes
  package.json
  src/v1/grafeas_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: automerge, cla: yes

#217 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/grafeas_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#219 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
