Repository googleapis/nodejs-grafeas, pull requests merged in 2020-05, with the labels that each got.

#157 fix: regenerate unit tests
  synth.metadata
  test/gapic_grafeas_v1.ts
Labels: automerge, cla: yes

#158 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#159 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
